// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_guBVfRNpW1DR5dG14xsTEokl2kfCgRA',
    appId: '1:150582503310:web:e3808e5d22d542dc38a6df',
    messagingSenderId: '150582503310',
    projectId: 'pluvia-cafe',
    authDomain: 'pluvia-cafe.firebaseapp.com',
    storageBucket: 'pluvia-cafe.firebasestorage.app',
    measurementId: 'G-X069N0J285',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4WJg8PgXeh8j5Jcq26o5dlP_0e0ugGcw',
    appId: '1:150582503310:android:566b8a98a488a5dc38a6df',
    messagingSenderId: '150582503310',
    projectId: 'pluvia-cafe',
    storageBucket: 'pluvia-cafe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD-446z0MWww5GiWlaUw46vYpR-2cocg0',
    appId: '1:150582503310:ios:2a25a02f4175592f38a6df',
    messagingSenderId: '150582503310',
    projectId: 'pluvia-cafe',
    storageBucket: 'pluvia-cafe.firebasestorage.app',
    iosClientId:
        '150582503310-2i7tgbgkrm1teccbinq3r8it5cjo705p.apps.googleusercontent.com',
    iosBundleId: 'com.example.sysCafeteria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD-446z0MWww5GiWlaUw46vYpR-2cocg0',
    appId: '1:150582503310:ios:2a25a02f4175592f38a6df',
    messagingSenderId: '150582503310',
    projectId: 'pluvia-cafe',
    storageBucket: 'pluvia-cafe.firebasestorage.app',
    iosClientId:
        '150582503310-2i7tgbgkrm1teccbinq3r8it5cjo705p.apps.googleusercontent.com',
    iosBundleId: 'com.example.sysCafeteria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_guBVfRNpW1DR5dG14xsTEokl2kfCgRA',
    appId: '1:150582503310:web:a515f5fedcd4397d38a6df',
    messagingSenderId: '150582503310',
    projectId: 'pluvia-cafe',
    authDomain: 'pluvia-cafe.firebaseapp.com',
    storageBucket: 'pluvia-cafe.firebasestorage.app',
    measurementId: 'G-BH17HHYRS0',
  );
}
